// ══════════════════════════════════════════════════════
// SAVOLLAR BAZASI
// ══════════════════════════════════════════════════════

const questions = {

  // ── Business English (100 ta savol) ──────────────────
  business_english: [
    { question: "The process of converting analog information into digital format is called —", options: ["A) Digitization", "B) Automation", "C) Outsourcing", "D) Encryption"], answer: "A" },
    { question: '"Productivity" means —', options: ["A) the ability to produce more work efficiently", "B) the process of selling goods abroad", "C) a method of reducing costs", "D) a type of business partnership"], answer: "A" },
    { question: "High productivity usually helps —", options: ["A) increase imports and reduce exports", "B) increase profits and save time", "C) reduce the number of employees", "D) lower the quality of products"], answer: "B" },
    { question: "Delaying tasks intentionally is called —", options: ["A) multitasking", "B) outsourcing", "C) procrastination", "D) automation"], answer: "C" },
    { question: "Time management is important for —", options: ["A) reducing product features", "B) working efficiently and meeting deadlines", "C) increasing inflation", "D) setting interest rates"], answer: "B" },
    { question: "Petty corruption involves —", options: ["A) high-level officials and large amounts of money", "B) international trade agreements", "C) small bribes and misuse of power in daily situations", "D) digital fraud and hacking"], answer: "C" },
    { question: "Grand corruption usually involves —", options: ["A) street vendors and small businesses", "B) high-level officials and large amounts of money", "C) small fines and local disputes", "D) insurance claims and refunds"], answer: "B" },
    { question: "Bribery means —", options: ["A) selling goods at a discount", "B) reporting illegal activity", "C) borrowing money from a bank", "D) giving or receiving money or gifts for unfair advantage"], answer: "D" },
    { question: "Cheating someone to get money illegally is called —", options: ["A) outsourcing", "B) fraud", "C) dividend", "D) upselling"], answer: "B" },
    { question: "Health insurance covers —", options: ["A) travel expenses and hotel costs", "B) company profits and losses", "C) medical expenses and treatment costs", "D) stock market investments"], answer: "C" },
    { question: "A person who reports corruption is called —", options: ["A) a shareholder", "B) a wholesaler", "C) a franchisee", "D) a whistleblower"], answer: "D" },
    { question: "Life insurance supports —", options: ["A) the government budget", "B) the family after a person's death", "C) the stock exchange", "D) business startups"], answer: "B" },
    { question: '"Claim" means —', options: ["A) a reduction in price", "B) a type of digital platform", "C) a request for payment from an insurance company", "D) a business partnership agreement"], answer: "C" },
    { question: "Hiring external companies from other countries is called —", options: ["A) franchising", "B) outsourcing", "C) upselling", "D) digitization"], answer: "B" },
    { question: "Insurance companies mainly —", options: ["A) manufacture goods and products", "B) provide digital marketing services", "C) manage stock exchange transactions", "D) provide financial protection against risks"], answer: "D" },
    { question: '"Deadline" means —', options: ["A) a type of business loan", "B) the final date or time to complete something", "C) a stock market indicator", "D) a method of increasing productivity"], answer: "B" },
    { question: '"Deal with complaints" means —', options: ["A) reduce product prices", "B) increase business profits", "C) handle or solve customer complaints", "D) export goods to other countries"], answer: "C" },
    { question: '"Customer satisfaction" is important because —', options: ["A) it reduces taxes for companies", "B) it helps keep customers loyal and improves business success", "C) it increases the interest rate", "D) it lowers the inflation rate"], answer: "B" },
    { question: '"Revenue" means —', options: ["A) money borrowed from a bank", "B) income earned by a business", "C) a reduction in product quality", "D) the cost of manufacturing"], answer: "B" },
    { question: '"Loss" means —', options: ["A) income earned by a business", "B) money paid to shareholders", "C) money lost when expenses are greater than income", "D) a type of insurance policy"], answer: "C" },
    { question: '"Entrepreneur" is —', options: ["A) a person who buys shares in a company", "B) a government official who manages trade", "C) a person who starts and manages a business", "D) a person who sells goods in bulk"], answer: "C" },
    { question: '"Startup" usually means —', options: ["A) a large established corporation", "B) a new business with growth potential", "C) a government-owned company", "D) a type of insurance policy"], answer: "B" },
    { question: '"Target market" means —', options: ["A) the total value of exports in a country", "B) the group of customers a business wants to sell to", "C) a method of reducing production costs", "D) the percentage of jobless people"], answer: "B" },
    { question: '"Unemployment" refers to —', options: ["A) the rise in price of goods and services", "B) the exchange of goods between countries", "C) the condition of people not having jobs but looking for work", "D) the profit shared among shareholders"], answer: "C" },
    { question: "GDP measures —", options: ["A) the number of unemployed people in a country", "B) the total debt of a country", "C) the interest rate charged by banks", "D) the total value of goods and services produced in a country"], answer: "D" },
    { question: '"Import" means —', options: ["A) selling goods or services to another country", "B) producing goods using automation", "C) buying goods or services from another country", "D) exchanging currency between countries"], answer: "C" },
    { question: '"Export" means —', options: ["A) buying goods or services from another country", "B) selling goods or services to another country", "C) borrowing money from international banks", "D) hiring workers from abroad"], answer: "B" },
    { question: "Economic growth usually increases —", options: ["A) inflation and trade deficits", "B) interest rates and loan capital", "C) employment and income", "D) insurance premiums and claims"], answer: "C" },
    { question: "GNP stands for —", options: ["A) General Net Payments", "B) Gross National Product", "C) Government Net Profit", "D) Global Network Platform"], answer: "B" },
    { question: "A logo is —", options: ["A) a financial document of a company", "B) a type of insurance policy", "C) a method of manufacturing goods", "D) a symbol or design representing a company or brand"], answer: "D" },
    { question: "Exporting means —", options: ["A) buying products from foreign companies", "B) selling products or services in other countries", "C) reducing domestic production", "D) managing internal business operations"], answer: "B" },
    { question: "Unemployment rate shows —", options: ["A) the total value of goods produced", "B) the percentage of the labor force that is jobless", "C) the interest rate of central banks", "D) the inflation rate of the economy"], answer: "B" },
    { question: '"Discount" means —', options: ["A) a type of business loan", "B) an increase in product quality", "C) a reduction in price", "D) a government tax on imports"], answer: "C" },
    { question: "Inflation is shown when —", options: ["A) the number of jobs increases rapidly", "B) the interest rates fall sharply", "C) prices of goods and services increase over time", "D) the stock market rises steadily"], answer: "C" },
    { question: "The action that increases customer satisfaction MOST is —", options: ["A) reducing the number of products", "B) raising the price of goods", "C) cutting marketing budgets", "D) providing excellent customer service"], answer: "D" },
    { question: "The contract between the insurer and the customer is called —", options: ["A) a franchise agreement", "B) an insurance policy", "C) a trade deficit", "D) a loan capital contract"], answer: "B" },
    { question: "A refund means —", options: ["A) a payment made to shareholders", "B) an increase in product price", "C) money returned to a customer after purchase", "D) a type of business investment"], answer: "C" },
    { question: "When a country imports more than it exports, it has a —", options: ["A) trade surplus", "B) balance of payments", "C) trade deficit", "D) gross national product"], answer: "C" },
    { question: "The difference between money coming into and going out of the country is called —", options: ["A) GDP", "B) trade deficit", "C) balance of payments", "D) interest rate"], answer: "C" },
    { question: "Gender inequality index measures —", options: ["A) the number of women in the workforce", "B) inequality between men and women", "C) the education level of citizens", "D) the average income of households"], answer: "B" },
    { question: '"Multitasking" means —', options: ["A) managing a large business team", "B) producing goods in large quantities", "C) doing several tasks at the same time", "D) outsourcing work to other companies"], answer: "C" },
    { question: '"Creativity" helps businesses by —', options: ["A) reducing the number of employees needed", "B) increasing interest rates", "C) developing new ideas and solving problems", "D) lowering the cost of insurance"], answer: "C" },
    { question: 'In the sentence "The gross ___ product is at an all-time high," the missing word is —', options: ["A) national", "B) domestic", "C) general", "D) global"], answer: "B" },
    { question: "Cybersecurity protects —", options: ["A) manufacturing plants and machinery", "B) insurance companies and banks", "C) government trade agreements", "D) computer systems, networks, and data"], answer: "D" },
    { question: "Digital marketing uses —", options: ["A) traditional newspapers and magazines", "B) physical stores and billboards", "C) the internet and digital technologies", "D) government-sponsored advertisements"], answer: "C" },
    { question: "A warning sign of a possible problem or danger is called —", options: ["A) a trade deficit", "B) a risk indicator", "C) a whistleblower", "D) a franchise fee"], answer: "B" },
    { question: "Which of the following is an example of a digital platform?", options: ["A) A local grocery store", "B) A manufacturing factory", "C) YouTube", "D) A physical market"], answer: "C" },
    { question: "Which is an example of the Digital Services Economy?", options: ["A) A traditional bookstore", "B) A local bus service", "C) Online banking and e-commerce", "D) A physical supermarket"], answer: "C" },
    { question: "The opposite of 'living abroad' is —", options: ["A) working as an expatriate", "B) experiencing brain drain", "C) living in one's home country", "D) studying in a foreign university"], answer: "C" },
    { question: "Someone living abroad for work is called —", options: ["A) a wholesaler", "B) a street vendor", "C) an expatriate (expat)", "D) a stockbroker"], answer: "C" },
    { question: "Brain drain is —", options: ["A) the rise of digital technologies in education", "B) a method of increasing national productivity", "C) a type of outsourcing used in manufacturing", "D) the emigration of skilled and educated people to another country"], answer: "D" },
    { question: "Reaction or opinion about something is called —", options: ["A) upsell", "B) feedback", "C) claim", "D) dividend"], answer: "B" },
    { question: "Global trade is —", options: ["A) the movement of workers between countries", "B) the exchange of goods and services between countries", "C) the management of a country's internal economy", "D) the production of goods using digital technologies"], answer: "B" },
    { question: '"Just-in-time" means —', options: ["A) delivering products ahead of the deadline", "B) producing goods in large batches for storage", "C) receiving materials or producing goods only when needed", "D) managing customer complaints immediately"], answer: "C" },
    { question: "Kaizen is —", options: ["A) a type of manufacturing machine", "B) a Japanese insurance system", "C) a philosophy of continuous improvement", "D) a digital marketing strategy"], answer: "C" },
    { question: "Lean manufacturing is —", options: ["A) a method of producing goods using robots only", "B) a production method focused on reducing waste and increasing efficiency", "C) a system for managing customer complaints", "D) a strategy for expanding into foreign markets"], answer: "B" },
    { question: "The use of smart machines and digital systems in production is called —", options: ["A) outsourcing", "B) franchising", "C) automation", "D) digitization"], answer: "C" },
    { question: '"Manufacturing" means —', options: ["A) the exchange of goods between countries", "B) the process of making goods or products", "C) the management of financial resources", "D) the promotion of products online"], answer: "B" },
    { question: "The manufacturing method that creates products layer by layer is —", options: ["A) lean manufacturing", "B) just-in-time production", "C) 3D printing", "D) kaizen method"], answer: "C" },
    { question: '"Value for money" means —', options: ["A) selling products at the lowest possible price", "B) good quality compared to the price paid", "C) offering discounts to loyal customers", "D) the total revenue earned by a business"], answer: "B" },
    { question: "Upsell is —", options: ["A) selling products at a discount", "B) returning money to a customer", "C) encouraging customers to buy a more expensive product or service", "D) a method of reducing business costs"], answer: "C" },
    { question: '"Characteristics of a product" are called —', options: ["A) targets", "B) revenues", "C) features", "D) dividends"], answer: "C" },
    { question: "What the buyer wants or expects is called —", options: ["A) customer needs", "B) target market", "C) loss leader", "D) upsell"], answer: "A" },
    { question: '"Who the product is for" describes —', options: ["A) the supplier", "B) the franchisee", "C) the investor", "D) the target market"], answer: "D" },
    { question: '"Buy one, get one free" is a type of —', options: ["A) franchising", "B) outsourcing", "C) promotion", "D) dividend"], answer: "C" },
    { question: 'In the sentence "The iPhone has many useful ___ such as a high-quality camera," the missing word is —', options: ["A) targets", "B) dividends", "C) revenues", "D) features"], answer: "D" },
    { question: "The business model that gives permission to use a brand is —", options: ["A) sole proprietorship", "B) franchising", "C) partnership", "D) outsourcing"], answer: "B" },
    { question: "A franchisee pays the franchisor —", options: ["A) dividends and shares", "B) royalties and franchise fees", "C) insurance premiums and claims", "D) interest rates and loan capital"], answer: "B" },
    { question: "The initial cost for starting a franchise is called —", options: ["A) dividend", "B) capital", "C) franchise fee", "D) interest rate"], answer: "C" },
    { question: "A financial protection against possible future losses or risks is —", options: ["A) outsourcing", "B) investment", "C) insurance", "D) franchising"], answer: "C" },
    { question: "An end-user is —", options: ["A) a person who manufactures goods", "B) the final person who uses a product or service", "C) a company that provides raw materials", "D) a business partner in a franchise"], answer: "B" },
    { question: "A person who buys goods or services for their own use is —", options: ["A) a wholesaler", "B) a supplier", "C) a stockbroker", "D) a consumer"], answer: "D" },
    { question: "Someone who sells things from a small stall or cart in the street is —", options: ["A) a wholesaler", "B) a street vendor", "C) a franchisee", "D) an investor"], answer: "B" },
    { question: "A person or company that provides goods or materials to another business is a —", options: ["A) consumer", "B) shareholder", "C) supplier", "D) franchisee"], answer: "C" },
    { question: 'A "loss leader" is —', options: ["A) a product sold at a very low price to attract customers", "B) a type of business partnership", "C) a method of increasing productivity", "D) a warning sign of financial risk"], answer: "A" },
    { question: '"At a loss" means —', options: ["A) selling something at the original price without profit", "B) selling something for less than it cost", "C) buying goods in bulk at a discount", "D) receiving a refund from a company"], answer: "B" },
    { question: '"At cost" means —', options: ["A) selling something at a large profit", "B) buying goods with a discount", "C) selling something at the original price without profit", "D) paying interest on a business loan"], answer: "C" },
    { question: "Someone who buys and sells goods in large amounts to shops or businesses is —", options: ["A) a consumer", "B) a street vendor", "C) an entrepreneur", "D) a wholesaler"], answer: "D" },
    { question: 'In the sentence "The supermarket offered sugar as a ___ to attract more customers," the missing word is —', options: ["A) franchise fee", "B) loss leader", "C) dividend", "D) capital"], answer: "B" },
    { question: "A business owned and managed by a single individual is —", options: ["A) a partnership", "B) a corporation", "C) a sole proprietorship", "D) a franchise"], answer: "C" },
    { question: "A business owned and managed by two or more owners is —", options: ["A) a franchise", "B) a sole proprietorship", "C) a startup", "D) a partnership"], answer: "D" },
    { question: "A place where people buy and sell shares is —", options: ["A) an insurance company", "B) a bank", "C) a stock exchange", "D) a wholesale market"], answer: "C" },
    { question: "A small part of a company that can be bought is —", options: ["A) a dividend", "B) a share (stock)", "C) a capital", "D) a claim"], answer: "B" },
    { question: "A person who owns shares in a company is —", options: ["A) a wholesaler", "B) a franchisee", "C) a shareholder", "D) a supplier"], answer: "C" },
    { question: "A person who buys/sells stocks for others is —", options: ["A) an investor", "B) an entrepreneur", "C) a consumer", "D) a stockbroker (broker)"], answer: "D" },
    { question: "Part of the company's profit paid to shareholders is —", options: ["A) interest rate", "B) capital", "C) dividend", "D) claim"], answer: "C" },
    { question: "A person who puts money into a business is —", options: ["A) a supplier", "B) an investor", "C) a wholesaler", "D) a franchisee"], answer: "B" },
    { question: "When prices are rising, this situation is called —", options: ["A) deflation", "B) trade deficit", "C) inflation", "D) recession"], answer: "C" },
    { question: "When prices are falling, this situation is called —", options: ["A) inflation", "B) deflation", "C) stagnation", "D) recession"], answer: "B" },
    { question: "The chance of losing money is called —", options: ["A) capital", "B) dividend", "C) risk", "D) interest"], answer: "C" },
    { question: "The percentage charged or paid for borrowing or saving money is —", options: ["A) dividend", "B) interest rate", "C) franchise fee", "D) capital"], answer: "B" },
    { question: "The request to receive money after a loss is called —", options: ["A) refund", "B) dividend", "C) claim", "D) capital"], answer: "C" },
    { question: "The money that a company uses to operate and develop is —", options: ["A) dividend", "B) interest rate", "C) claim", "D) capital"], answer: "D" },
    { question: "Loan capital is —", options: ["A) the profit shared among shareholders", "B) a fee paid to start a franchise", "C) money borrowed by a business that must be repaid with interest", "D) the total income earned by a company"], answer: "C" },
    { question: 'In the sentence "The stock ___ is a place where people buy and sell company shares," the missing word is —', options: ["A) market", "B) exchange", "C) capital", "D) bank"], answer: "B" },
    { question: 'In the sentence "There is always a ___ in investing," the missing word is —', options: ["A) profit", "B) capital", "C) dividend", "D) risk"], answer: "D" },
    { question: 'In the sentence "Many people buy ___ in big companies like Apple or Google," the missing word is —', options: ["A) dividends", "B) shares", "C) capitals", "D) claims"], answer: "B" },
    { question: 'In a "bull market" —', options: ["A) stock prices are falling", "B) the economy is in recession", "C) interest rates are very high", "D) stock prices are rising"], answer: "D" },
    { question: 'In the sentence "If the ___ grows, your shares become more valuable," the missing word is —', options: ["A) market", "B) stock", "C) company", "D) capital"], answer: "C" },
    { question: "Indicators are —", options: ["A) a type of business insurance policy", "B) statistics or signs that show economic or business conditions", "C) methods of increasing product sales", "D) tools for managing customer complaints"], answer: "B" },
  ],

  // ── Raqamli biznesni boshqarish ──────────────────────
  raqamli_biznes: [
    { question: "E-commerce nima?", options: ["A) Elektron pochta", "B) Internet orqali tovar/xizmat sotish", "C) Raqamli valyuta", "D) Onlayn o'yin"], answer: "B" },
    { question: "SEO nima uchun ishlatiladi?", options: ["A) Saytni bezash uchun", "B) Qidiruv tizimida yuqori o'rinni egallash uchun", "C) Xabarlar yuborish uchun", "D) To'lov qabul qilish uchun"], answer: "B" },
    { question: "KPI nima?", options: ["A) Kompaniya nomi", "B) Moliyaviy hisobot", "C) Maqsad bajarilishini o'lchash ko'rsatkichi", "D) Marketing strategiyasi"], answer: "C" },
    { question: "CRM tizimi nima uchun kerak?", options: ["A) Mahsulot ishlab chiqarish", "B) Mijozlar bilan munosabatlarni boshqarish", "C) Buxgalteriya", "D) Xodimlarni nazorat qilish"], answer: "B" },
    { question: "Raqamli marketing kanallaridan biri emas?", options: ["A) Social media", "B) Email marketing", "C) Billboard reklama", "D) SEO"], answer: "C" },
    { question: "MVP (biznesda) nima?", options: ["A) Eng qimmat mahsulot", "B) Minimal darajadagi tayyor mahsulot", "C) Maksimal foyda", "D) Marketing reja"], answer: "B" },
    { question: "Konversiya darajasi nima?", options: ["A) Saytga tashrif buyuruvchilar soni", "B) Reklama narxi", "C) Tashrif buyuruvchidan mijozga aylanish foizi", "D) Mahsulot narxi"], answer: "C" },
    { question: "SaaS nima?", options: ["A) Dasturiy ta'minot xizmat sifatida", "B) Sotish strategiyasi", "C) Ijtimoiy tarmoq", "D) To'lov tizimi"], answer: "A" },
    { question: "Dropshipping modelida qanday ishlaydi?", options: ["A) Tovarni o'zingiz saqlaysiz", "B) Tovarni yetkazib beruvchidan to'g'ridan-to'g'ri buyurtmachiga yetkazasiz", "C) Mahsulot ishlab chiqarasiz", "D) Faqat reklama qilasiz"], answer: "B" },
    { question: "Raqamli biznesda 'funnel' nima?", options: ["A) Moliyaviy hisobot", "B) Mijozni jalb qilishdan sotishgacha bo'lgan jarayon", "C) Reklama turi", "D) Mahsulot kategoriyasi"], answer: "B" },
  ],
};

module.exports = questions;
